exclude: ['README.md']
timezone: US/Eastern
talks:
  -
    title: Geolocation of Social Media Users
    detail: Poster Presentation @ ACL 2015
    url: "https://drive.google.com/open?id=0B9ZfPKPvp-JieG45QmgtS3pWTTA"
    img: "aclposter.jpg"
  -
    title: Geolocation of Social Media Users
    detail: Poster Presentation @ NAACL 2015
    url: "https://drive.google.com/open?id=0B9ZfPKPvp-JiYnp6Q01wa1FfN3M"
    img: "naaclposter.jpg"

papers:
  - layout: paper
    paper-type: inproceedings
    selected: yes
    year: 2019
    img: acl2019
    title: Massively Multilingual Transfer for NER
    doc-url: https://arxiv.org/abs/1902.00193
    authors: Afshin Rahimi, Yuan Li, and Trevor Cohn
    booktitle: ACL 2019.
    booktitle-url: http://acl2019.org
    venue: Main Conference
    code: https://github.com/afshinrahimi/mmner
    abstract: > 
	     In cross-lingual transfer, NLP models over one
	or more source languages are applied to a low-
	resource target language. While most prior
	work has used a single source model or a
	few carefully selected models, here we consider 
	a “massive” setting with many such mod-
	els. This setting raises the problem of poor
	transfer, particularly from distant languages.
	We propose two techniques for modulating
	the transfer, suitable for zero-shot or few-shot
	learning, respectively. Evaluating on named
	entity recognition, we show that our tech-
	niques are much more effective than strong
	baselines, including standard ensembling, and
	our unsupervised method rivals oracle selec-
	tion of the single best individual model.

  - layout: paper
    paper-type: inproceedings
    selected: yes
    year: 2018
    img: acl2018
    title: Semi-supervised User Geolocation via Graph Convolutional Networks
    doc-url: https://arxiv.org/abs/1804.08049
    authors: Afshin Rahimi, Trevor Cohn and Timothy Baldwin
    booktitle: ACL 2018.
    booktitle-url: http://acl2018.org
    venue: Main Conference
    code: https://github.com/afshinrahimi/geographconv
    abstract: > 
      Social media user geolocation is vital to many applications such as event detection.
      In this paper, we propose GCN, a multiview geolocation model based on Graph Convolutional Networks,
      that uses both text and network context. We compare GCN to the state-of-the-art, 
      and to two baselines we propose, and show that our model achieves or is 
      competitive with the state-of-the-art over three benchmark geolocation datasets 
      when sufficient supervision is available. 
      We also evaluate GCN under a minimal supervision scenario, 
      and show it outperforms baselines. We find that highway network 
      gates are essential for controlling the amount of useful 
      neighbourhood expansion in GCN.
      
  - layout: paper
    paper-type: inproceedings
    selected: yes
    year: 2017
    img: emnlp2017
    title: Continuous Representation of Location for Geolocation and Lexical Dialectology using Mixture Density Networks
    doc-url: https://drive.google.com/open?id=0B9ZfPKPvp-JickpYa0drZWQxcHc
    authors: Afshin Rahimi, Timothy Baldwin and Trevor Cohn
    booktitle: EMNLP 2017.
    booktitle-url: http://emnlp2017.net
    venue: Main Conference
    code: https://github.com/afshinrahimi/geomdn
    abstract: > 
      We propose a method for embedding two-
      dimensional locations in a continuous vec-
      tor space using a neural network-based
      model incorporating mixtures of Gaussian
      distributions, presenting two model vari-
      ants for text-based geolocation and lexi-
      cal dialectology. Evaluated over Twitter
      data, the proposed model outperforms con-
      ventional regression-based geolocation and
      provides a better estimate of uncertainty.
      We also show the effectiveness of the rep-
      resentation for predicting words from loca-
      tion in lexical dialectology, and evaluate it
      using the DARE dataset.

  - layout: paper
    paper-type: inproceedings
    selected: yes
    year: 2017
    img: acl2017
    title: A Neural Model for User Geolocation and Lexical Dialectology
    doc-url: https://arxiv.org/pdf/1704.04008.pdf
    authors: Afshin Rahimi, Trevor Cohn and Timothy Baldwin
    booktitle: ACL 2017, Short papers.
    booktitle-url: http://acl2017.org
    venue: Main Conference
    code: https://github.com/afshinrahimi/acl2017
    abstract: > 
      We propose a simple yet effective textbased
      user geolocation model based on
      a neural network with one hidden layer,
      which achieves state of the art performance
      over three Twitter benchmark geolocation
      datasets, in addition to producing word and
      phrase embeddings in the hidden layer that
      we show to be useful for detecting dialectal
      terms. As part of our analysis of dialectal
      terms, we release DAREDS, a dataset for
      evaluating dialect term detection methods.

  - layout: paper
    paper-type: inproceedings
    selected: yes
    year: 2016
    img: acl2016
    title: pigeo, A Python Geotagging Tool
    doc-url: http://www.aclweb.org/anthology/P16-4022
    authors: Afshin Rahimi, Trevor Cohn and Timothy Baldwin
    booktitle: ACL 2016, Demonstration papers.
    booktitle-url: http://acl2016.org
    venue: Main Conference
    code: https://github.com/afshinrahimi/pigeo
    abstract: > 
      We present pigeo, a Python geolocation
      prediction tool that predicts a location for
      a given text input or Twitter user. We discuss
      the design, implementation and application
      of pigeo, and empirically evaluate it.
      pigeo is able to geolocate informal
      text and is a very useful tool for users who
      require a free and easy-to-use, yet accurate
      geolocation service based on pre-trained
      models. Additionally, users can train their
      own models easily using pigeo’s API.
      
  - layout: paper
    paper-type: inproceedings
    selected: yes
    year: 2015
    img: acl2015
    title: Twitter User Geolocation Using a Unified Text and Network Prediction Model
    doc-url: http://www.aclweb.org/anthology/P15-2104
    authors: Afshin Rahimi, Trevor Cohn and Timothy Baldwin
    booktitle: ACL 2015, Short papers.
    booktitle-url: http://acl2015.org
    venue: Main Conference
    code: https://github.com/afshinrahimi/geolocation/
    abstract: > 
      Abstract We propose a label propagation approach to
      geolocation prediction based on Modified Adsorption,
      with two enhancements: (1) the removal
      of “celebrity” nodes to increase location
      homophily and boost tractability; and (2) the
      incorporation of text-based geolocation priors
      for test users. Experiments over three Twitter
      benchmark datasets achieve state-of-the-art results,
      and demonstrate the effectiveness of the
      enhancements.

  - layout: paper
    paper-type: inproceedings
    selected: yes
    year: 2015
    img: naacl2015
    title: Exploiting text and network context for geolocation of social media users
    doc-url: http://www.aclweb.org/anthology/N15-1153
    authors: Afshin Rahimi, Duy Vu, Trevor Cohn and Timothy Baldwin
    booktitle: NAACL-HLT 2015, Short papers.
    booktitle-url: http://naacl.org/naacl-hlt-2015/
    venue: Main Conference
    code: https://github.com/afshinrahimi/geolocation/
    abstract: > 
      Abstract Research on automatically geolocating social
      media users has conventionally been based on
      the text content of posts from a given user or
      the social network of the user, with very little
      crossover between the two, and no benchmarking
      of the two approaches over comparable
      datasets. We bring the two threads of research
      together in first proposing a text-based
      method based on adaptive grids, followed by a
      hybrid network- and text-based method. Evaluating
      over three Twitter datasets, we show
      that the empirical difference between textand
      network-based methods is not great, and
      that hybridisation of the two is superior to
      the component methods, especially in contexts
      where the user graph is not well connected.
      We achieve state-of-the-art results on all three
      datasets.
