exclude: ['README.md']
timezone: US/Eastern
talks:
  -
    title: Geolocation of Social Media Users
    detail: Poster Presentation @ ACL 2015
    url: "https://drive.google.com/open?id=0B9ZfPKPvp-JieG45QmgtS3pWTTA"
    img: "aclposter.jpg"
  -
    title: Geolocation of Social Media Users
    detail: Poster Presentation @ NAACL 2015
    url: "https://drive.google.com/open?id=0B9ZfPKPvp-JiYnp6Q01wa1FfN3M"
    img: "naaclposter.jpg"

papers:
  - layout: paper
    paper-type: inproceedings
    selected: yes
    year: 2017
    img: acl2017
    title: A Neural Model for User Geolocation and Lexical Dialectology
    doc-url: https://arxiv.org/pdf/1704.04008.pdf
    authors: Afshin Rahimi, Trevor Cohn and Timothy Baldwin
    booktitle: ACL 2017, Short papers.
    booktitle-url: http://acl2017.org
    venue: Main Conference
    code: https://github.com/afshinrahimi/acl2017
    abstract: > 
      We propose a simple yet effective textbased
      user geolocation model based on
      a neural network with one hidden layer,
      which achieves state of the art performance
      over three Twitter benchmark geolocation
      datasets, in addition to producing word and
      phrase embeddings in the hidden layer that
      we show to be useful for detecting dialectal
      terms. As part of our analysis of dialectal
      terms, we release DAREDS, a dataset for
      evaluating dialect term detection methods.

  - layout: paper
    paper-type: inproceedings
    selected: yes
    year: 2015
    img: acl2015
    title: Twitter User Geolocation Using a Unified Text and Network Prediction Model
    doc-url: http://www.aclweb.org/anthology/P15-2104
    authors: Afshin Rahimi, Trevor Cohn and Timothy Baldwin
    booktitle: ACL 2015, Short papers.
    booktitle-url: http://acl2015.org
    venue: Main Conference
    code: https://github.com/afshinrahimi/geolocation/
    abstract: > 
      Abstract We propose a label propagation approach to
      geolocation prediction based on Modified Adsorption,
      with two enhancements: (1) the removal
      of “celebrity” nodes to increase location
      homophily and boost tractability; and (2) the
      incorporation of text-based geolocation priors
      for test users. Experiments over three Twitter
      benchmark datasets achieve state-of-the-art results,
      and demonstrate the effectiveness of the
      enhancements.

  - layout: paper
    paper-type: inproceedings
    selected: yes
    year: 2015
    img: naacl2015
    title: Exploiting text and network context for geolocation of social media users
    doc-url: http://www.aclweb.org/anthology/N15-1153
    authors: Afshin Rahimi, Duy Vu, Trevor Cohn and Timothy Baldwin
    booktitle: NAACL-HLT 2015, Short papers.
    booktitle-url: http://naacl.org/naacl-hlt-2015/
    venue: Main Conference
    code: https://github.com/afshinrahimi/geolocation/
    abstract: > 
      Abstract Research on automatically geolocating social
      media users has conventionally been based on
      the text content of posts from a given user or
      the social network of the user, with very little
      crossover between the two, and no benchmarking
      of the two approaches over comparable
      datasets. We bring the two threads of research
      together in first proposing a text-based
      method based on adaptive grids, followed by a
      hybrid network- and text-based method. Evaluating
      over three Twitter datasets, we show
      that the empirical difference between textand
      network-based methods is not great, and
      that hybridisation of the two is superior to
      the component methods, especially in contexts
      where the user graph is not well connected.
      We achieve state-of-the-art results on all three
      datasets.
