exclude: ['README.md']
timezone: US/Eastern
talks:
  -
    title: Geolocation of Social Media Users
    detail: Poster Presentation @ ACL 2015
    url: "https://drive.google.com/open?id=0B9ZfPKPvp-JieG45QmgtS3pWTTA"
    img: "upstate-map.png"

papers:
  - layout: paper
    paper-type: inproceedings
    selected: yes
    year: 2015
    img: acl2015
    title: Twitter User Geolocation Using a Unified Text and Network Prediction Model
    doc-url: http://www.aclweb.org/anthology/P15-2104
    authors: Afshin Rahimi, Trevor Cohn and Timothy Baldwin
    booktitle: ACL 2015, Short papers.
    booktitle-url: http://acl2015.org
    venue: Main Conference
    code: https://github.com/afshinrahimi/textylon/
    abstract: > 
      Abstract We propose a label propagation approach to
      geolocation prediction based on Modified Adsorption,
      with two enhancements: (1) the removal
      of “celebrity” nodes to increase location
      homophily and boost tractability; and (2) the
      incorporation of text-based geolocation priors
      for test users. Experiments over three Twitter
      benchmark datasets achieve state-of-the-art results,
      and demonstrate the effectiveness of the
      enhancements.

  - layout: paper
    paper-type: inproceedings
    selected: yes
    year: 2015
    img: naacl2015
    title: Twitter User Geolocation Using a Unified Text and Network Prediction Model
    doc-url: http://www.aclweb.org/anthology/N15-1153
    authors: Afshin Rahimi, Trevor Cohn and Timothy Baldwin
    booktitle: ACL 2015, Short papers.
    booktitle-url: http://acl2015.org
    venue: Main Conference
    code: https://github.com/afshinrahimi/textylon/
    abstract: > 
      Abstract Research on automatically geolocating social
      media users has conventionally been based on
      the text content of posts from a given user or
      the social network of the user, with very little
      crossover between the two, and no benchmarking
      of the two approaches over comparable
      datasets. We bring the two threads of research
      together in first proposing a text-based
      method based on adaptive grids, followed by a
      hybrid network- and text-based method. Evaluating
      over three Twitter datasets, we show
      that the empirical difference between textand
      network-based methods is not great, and
      that hybridisation of the two is superior to
      the component methods, especially in contexts
      where the user graph is not well connected.
      We achieve state-of-the-art results on all three
      datasets.
